# set this to the location where Kochiku web is running
kochiku_web_host: "kochiku-server-41925.phx-os1.stratus.dev.ebay.com"

# Change this if you want to run Redis on a different machine than the build master
# This needs to be the same as the Redis instance that the Kochiku application uses
redis_host: "kochiku-server-41925.phx-os1.stratus.dev.ebay.com"

# Change this to the hostnames for the kochiku worker boxes that you want to deploy to
worker_hosts:
  - kochiku-worker-1-41926.phx-os1.stratus.dev.ebay.com
  - 10.9.221.250
  - 10.9.221.242
  - 10.9.221.240
  - 10.9.221.239
  - 10.9.221.215
  - 10.9.221.196
  - 10.9.222.150
  - 10.9.222.152
  - 10.9.222.171
  - 10.9.222.173
  - 10.9.250.175
  - 10.9.211.223
  - 10.9.211.172
  - 10.9.211.16
  - 10.9.211.131
  - 10.9.222.43
  - 10.9.211.37
  - 10.9.215.19
  - 10.9.211.52
  

